### ISSUE TITLE
不會自動簽到

### ISSUE THREAD

**Issue by vonnoq** [brownsugar/baha-auto-sign#1]
小屋已經無法簽到

必須在巴哈首頁面

**Comment by brownsugar** [comment]
Hi，
目前測試小屋還是支援簽到功能的，請問您遇到的情況是無法跳出簽到嗎？
可以的話也麻煩提供小屋網址供確認，謝謝。

**Comment by vonnoq** [comment]
是的，只會開啟小屋頁面
我在猜是不是新版小屋沒辦法簽到？
我現在剛切回舊版，可能要明天才能確認
新版小屋：https://home.gamer.com.tw/profile/index.php?&owner=qaz1022

**Comment by brownsugar** [comment]
感謝回報，今天簽到確實在小屋不會觸發了（我的是維持新版的，到昨天都正常），確認中。

**Comment by brownsugar** [comment]
明天測試沒問題後就會發佈修正，屆時再麻煩協助確認。

**Comment by vonnoq** [comment]
沒問題了，謝謝！
